[package]
name = "shared_lib_web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sharedlib = { path = "../shared_lib" }
wasm-bindgen = "0.2.87"
