[package]
name = "sharedlib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = [
  "staticlib", # must for iOS
  "rlib",
  "cdylib",    # must for Android
]

[dependencies]
uniffi = { workspace = true }
uniffi_bindgen = { workspace = true }
sha2 = { version = "0.10.8", features = [] }

[build-dependencies]
uniffi = { workspace = true, features = ["build", "cli"] }
